Entity/HotelsRooms.php
<?php

namespace CMS\HotelsBundle\Entity;

/**
 * HotelsRooms
 */
class HotelsRooms
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var array
     */
    private $title;

    /**
     * @var integer
     */
    private $hotel;

    /**
     * @var int
     */
    private $count_rooms = 0;

    /**
     * @var int
     */
    private $count_bedrooms = 0;

    /**
     * @var int
     */
    private $count_bathrooms = 0;

    /**
     * @var float
     */
    private $price_day = 0.0;

    /**
     * @var float
     */
    private $price_additional_guest = 0.0;

    /**
     * @var int
     */
    private $count_guests = 1;

    /**
     * @var int
     */
    private $count_max_guests = 0;

    /**
     * @var string
     */
    private $descriptions;

    /**
     * @var integer
     */
    private $duration_reservation;

    /**
     * @var int
     */
    private $reservation_min_days;

    /**
     * @var ArrayCollection
     */
    private $services;

    /**
     * @var ArrayCollection
     */
    private $photos;

    /**
     * @var float
     */
    private $rating = 1.0;

    /**
     * @var int
     */
    private $count = 1;

    /**
     * @var int
     */
    private $status = 0;

    /**
     * @var ArrayCollection
     */
    private $reservations;

    /**
     * @var bool
     */
    private $is_published = false;

    /**
     * @var bool
     */
    private $is_deleted = false;

    /**
     * @var \DateTime
     */
    private $date_create;

    /**
     * @var \DateTime
     */
    private $date_update;

    /**
     * @var integer
     */
    private $create_by;

    /**
     * @var integer
     */
    private $update_by;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return array
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param array $title
     * @return HotelsRooms
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return int
     */
    public function getHotel()
    {
        return $this->hotel;
    }

    /**
     * @param int $hotel
     * @return HotelsRooms
     */
    public function setHotel($hotel)
    {
        $this->hotel = $hotel;

        return $this;
    }

    /**
     * @return int
     */
    public function getCountRooms()
    {
        return $this->count_rooms;
    }

    /**
     * @param int $count_rooms
     * @return HotelsRooms
     */
    public function setCountRooms($count_rooms)
    {
        $this->count_rooms = $count_rooms;

        return $this;
    }

    /**
     * @return int
     */
    public function getCountBedrooms()
    {
        return $this->count_bedrooms;
    }

    /**
     * @param int $count_bedrooms
     * @return HotelsRooms
     */
    public function setCountBedrooms($count_bedrooms)
    {
        $this->count_bedrooms = $count_bedrooms;

        return $this;
    }

    /**
     * @return int
     */
    public function getCountBathrooms()
    {
        return $this->count_bathrooms;
    }

    /**
     * @param int $count_bathrooms
     * @return HotelsRooms
     */
    public function setCountBathrooms($count_bathrooms)
    {
        $this->count_bathrooms = $count_bathrooms;

        return $this;
    }

    /**
     * @return float
     */
    public function getPriceDay()
    {
        return $this->price_day;
    }

    /**
     * @param float $price_day
     * @return HotelsRooms
     */
    public function setPriceDay($price_day)
    {
        $this->price_day = $price_day;

        return $this;
    }

    /**
     * @return float
     */
    public function getPriceAdditionalGuest()
    {
        return $this->price_additional_guest;
    }

    /**
     * @param float $price_additional_guest
     * @return HotelsRooms
     */
    public function setPriceAdditionalGuest($price_additional_guest)
    {
        $this->price_additional_guest = $price_additional_guest;

        return $this;
    }

    /**
     * @return int
     */
    public function getCountGuests()
    {
        return $this->count_guests;
    }

    /**
     * @param int $count_guests
     * @return HotelsRooms
     */
    public function setCountGuests($count_guests)
    {
        $this->count_guests = $count_guests;

        return $this;
    }

    /**
     * @return int
     */
    public function getCountMaxGuests()
    {
        return $this->count_max_guests;
    }

    /**
     * @param int $count_max_guests
     * @return HotelsRooms
     */
    public function setCountMaxGuests($count_max_guests)
    {
        $this->count_max_guests = $count_max_guests;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescriptions()
    {
        return $this->descriptions;
    }

    /**
     * @param string $descriptions
     * @return HotelsRooms
     */
    public function setDescriptions($descriptions)
    {
        $this->descriptions = $descriptions;

        return $this;
    }

    /**
     * @return int
     */
    public function getDurationReservation()
    {
        return $this->duration_reservation;
    }

    /**
     * @param int $duration_reservation
     * @return $this
     */
    public function setDurationReservation($duration_reservation)
    {
        $this->duration_reservation = $duration_reservation;

        return $this;
    }

    /**
     * @return int
     */
    public function getReservationMinDays()
    {
        return $this->reservation_min_days;
    }

    /**
     * @param int $reservation_min_days
     * @return HotelsRooms
     */
    public function setReservationMinDays($reservation_min_days)
    {
        $this->reservation_min_days = $reservation_min_days;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getServices()
    {
        return $this->services;
    }

    /**
     * @param ArrayCollection $services
     * @return HotelsRooms
     */
    public function setServices($services)
    {
        $this->services = $services;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getPhotos()
    {
        return $this->photos;
    }

    /**
     * @param ArrayCollection $photos
     * @return HotelsRooms
     */
    public function setPhotos($photos)
    {
        $this->photos = $photos;

        return $this;
    }

    /**
     * @return float
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * @param float $rating
     * @return HotelsRooms
     */
    public function setRating($rating)
    {
        $this->rating = $rating;

        return $this;
    }

    /**
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * @param int $count
     * @return HotelsRooms
     */
    public function setCount($count)
    {
        $this->count = $count;

        return $this;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     * @return HotelsRooms
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getReservations()
    {
        return $this->reservations;
    }

    /**
     * @param ArrayCollection $reservations
     * @return HotelsRooms
     */
    public function setReservations($reservations)
    {
        $this->reservations = $reservations;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsPublished()
    {
        return $this->is_published;
    }

    /**
     * @param boolean $is_published
     * @return HotelsRooms
     */
    public function setIsPublished($is_published)
    {
        $this->is_published = $is_published;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsDeleted()
    {
        return $this->is_deleted;
    }

    /**
     * @param boolean $is_deleted
     * @return HotelsRooms
     */
    public function setIsDeleted($is_deleted)
    {
        $this->is_deleted = $is_deleted;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * @param \DateTime $date_create
     * @return HotelsRooms
     */
    public function setDateCreate($date_create)
    {
        $this->date_create = $date_create;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateUpdate()
    {
        return $this->date_update;
    }

    /**
     * @param \DateTime $date_update
     * @return HotelsRooms
     */
    public function setDateUpdate($date_update)
    {
        $this->date_update = $date_update;

        return $this;
    }

    /**
     * @return int
     */
    public function getCreateBy()
    {
        return $this->create_by;
    }

    /**
     * @param int $create_by
     * @return HotelsRooms
     */
    public function setCreateBy($create_by)
    {
        $this->create_by = $create_by;

        return $this;
    }

    /**
     * @return int
     */
    public function getUpdateBy()
    {
        return $this->update_by;
    }

    /**
     * @param int $update_by
     * @return HotelsRooms
     */
    public function setUpdateBy($update_by)
    {
        $this->update_by = $update_by;

        return $this;
    }
}

Entity/HousingTypes.php
<?php

namespace CMS\HotelsBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * HousingTypes
 */
class HousingTypes
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    /**
     * @var integer
     */
    private $is_have_rooms;

    /**
     * @var ArrayCollection
     */
    private $hotels;

    /**
     * @var \DateTime
     */
    private $date_create;

    /**
     * @var \DateTime
     */
    private $date_update;

    /**
     * @var integer
     */
    private $create_by;

    /**
     * @var integer
     */
    private $update_by;

    public function __construct()
    {
        $this->hotels = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return HousingTypes
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @return int
     */
    public function getIsHaveRooms()
    {
        return $this->is_have_rooms;
    }

    /**
     * @param int $is_have_rooms
     * @return HousingTypes
     */
    public function setIsHaveRooms($is_have_rooms)
    {
        $this->is_have_rooms = $is_have_rooms;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getHotels()
    {
        return $this->hotels;
    }

    /**
     * @param ArrayCollection $hotels
     * @return $this
     */
    public function setHotels($hotels)
    {
        $this->hotels = $hotels;

        return $this;
    }

    /**
     * @return int
     */
    public function getCreateBy()
    {
        return $this->create_by;
    }

    /**
     * @param int $create_by
     * @return Locale
     */
    public function setCreateBy($create_by)
    {
        $this->create_by = $create_by;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * @param \DateTime $date_create
     * @return Locale
     */
    public function setDateCreate($date_create)
    {
        $this->date_create = new \DateTime();

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateUpdate()
    {
        return $this->date_update;
    }

    /**
     * @param \DateTime $date_update
     * @return Locale
     */
    public function setDateUpdate($date_update)
    {
        $this->date_update = new \DateTime();

        return $this;
    }

    /**
     * @return int
     */
    public function getUpdateBy()
    {
        return $this->update_by;
    }

    /**
     * @param int $update_by
     * @return Locale
     */
    public function setUpdateBy($update_by)
    {
        $this->update_by = $update_by;

        return $this;
    }
}

Resources/views/Twig/calendar.html.twig
{% if hotel %}
    <h3>{{ hotel.title|locale }}</h3>
        <div class="prices-calendar">
            <div class="control-panel clearfix">
                <div class="years form pull-left">
                    {% for _year in ('now'|date('Y'))..(('now'|date('Y'))+3) %}
                        <span class="year{% if year == _year %} active{% endif %}">
                        <a href="{{ url(app.request.get('_route'), {'hotel': hotel.id, 'year': _year}) }}">{{ _year }}</a>
                    </span>
                    {% endfor %}
                </div>
                <div class="controls form-inline pull-right"></div>
            </div>
            <table class="table table-bordered hotel_calendar">
                <tr>
                    <th></th>
                    {% for day in 1..31 %}
                        <th>{{ day }}</th>
                    {% endfor %}
                </tr>
                {% for month in 1..12 %}
                    <tr>
                        <td>{{ ('01.' ~ month ~ '.' ~ year)|date('M') }}</td>
                        {% for day in 1..31 %}
                            {% set count = 0 %}
                            {% set isActive = true %}
                            {% set date = (day ~ '.' ~ month ~ '.' ~ year)|date %}
                            {% set classes = ['green', 'selectable'] %}

                            {% if date|date('d.m.Y') in prices|keys and day <= ('01.' ~ month ~ '.' ~ year)|date('t') %}
                                {% if hotel.housingType.isHaveRooms %}
                                    {% for room in hotel.rooms %}
                                        {% if attribute(prices[date|date('d.m.Y')], room.id) is defined %}
                                            {% set price = attribute(prices[date|date('d.m.Y')], room.id) %}
                                            {% set count = count + price.count %}
                                            {% set isActive = price.is_active %}
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                    {% set price =  attribute(prices, date|date('d.m.Y')) %}
                                    {% set count = price.count %}
                                    {% set isActive = price.is_active %}
                                {% endif %}

                                {% if day > ('01.' ~ month ~ '.' ~ year)|date('t') or date|date('U') < 'now'|date('U') %}
                                    {% set classes = ['disabled'] %}
                                {% endif %}

                                {% set _reservations = reservations|count_reservation(hotel.id, null, date ) %}

                                {% if _reservations|length == 0 %}
                                    {% set classes = ['selectable', 'green'] %}
                                {% elseif count - reservations|length > 0 %}
                                    {% set classes = ['selectable', 'yellow'] %}
                                {% else %}
                                    {% set classes = ['selectable', 'red'] %}
                                {% endif %}

                                {% if not isActive %}
                                    {% set classes = ['selectable', 'stop-sales'] %}
                                {% endif %}
                            {% else %}
                                {% set classes = ['disabled'] %}
                            {% endif %}

                            <td data-date="{{ date|date('d.m.Y') }}"
                                data-hotel="{{ hotel.id }}"
                                data-status="{{ isActive }}">
                                <div class="{{ classes|join(' ') }}">
                                    {% if 'disabled' not in classes %}
                                        <small>{{ count - _reservations|length }}</small>
                                    {% else %}
                                        &nbsp;
                                    {% endif %}
                                </div>
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        </div>
{% endif %}

Resources/views/Twig/calendar_room.html.twig
{% if rooms|length %}
    {% for room in rooms %}
        <h3>{{ room.title|locale }}</h3>
        <div class="prices-calendar">
            <div class="control-panel clearfix">
                <div class="years form pull-left">
                    {% for _year in ('now'|date('Y'))..(('now'|date('Y'))+3) %}
                        <span class="year{% if year == _year %} active{% endif %}">
                        <a href="{{ url(app.request.get('_route'), {'hotel': hotel.id, 'room': room.id,'year': _year}) }}">{{ _year }}</a>
                    </span>
                    {% endfor %}
                </div>
                <div class="controls form-inline pull-right"></div>
            </div>
            <table class="table table-bordered hotel_calendar">
                <tr>
                    <th></th>
                    {% for day in 1..31 %}
                        <th>{{ day }}</th>
                    {% endfor %}
                </tr>
                {% for month in 1..12 %}
                    <tr>
                        <td>{{ ('01.' ~ month ~ '.' ~ year)|date('M') }}</td>
                        {% for day in 1..31 %}
                            {% set isActive = true %}
                            {% set date = (day ~ '.' ~ month ~ '.' ~ year)|date %}
                            {% set classes = ['green', 'selectable'] %}

                            {% if date|date('d.m.Y') in prices|keys and room.id in prices[date|date('d.m.Y')]|keys and day <= ('01.' ~ month ~ '.' ~ year)|date('t') %}
                                {% set price = prices[date|date('d.m.Y')][room.id] %}
                                {% set isActive = price.is_active %}
                                {% set count = price.count %}

                                {% if day > ('01.' ~ month ~ '.' ~ year)|date('t') or date|date('U') < 'now'|date('U') or price.is_active != true %}
                                    {% set classes = ['disabled'] %}
                                {% endif %}

                                {% set room_reservations = reservations|count_reservation(hotel.id, room.id, date ) %}

                                {% if room_reservations|length == 0 %}
                                    {% set classes = ['selectable', 'green'] %}
                                {% elseif count - room_reservations|length > 0 %}
                                    {% set classes = ['selectable', 'yellow'] %}
                                {% else %}
                                    {% set classes = ['selectable', 'red'] %}
                                {% endif %}

                                {% if not isActive %}
                                    {% set classes = ['selectable', 'stop-sales'] %}
                                {% endif %}
                            {% else %}
                                {% set classes = ['disabled'] %}
                            {% endif %}

                            <td data-date="{{ date|date('d.m.Y') }}"
                                data-hotel="{{ hotel.id }}"
                                data-room="{{ room.id }}"
                                data-status="{{ isActive }}">
                                <div class="{{ classes|join(' ') }}">
                                    {% if 'disabled' not in classes %}
                                        <small>{{ count - room_reservations|length }}</small>
                                    {% else %}
                                        &nbsp;
                                    {% endif %}
                                </div>
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endfor %}
{% endif %}

Resources/views/Twig/comments.html.twig
{% if comments|length > 0 %}
    {% for comment in comments %}
        <article>
            <p class="photo"><span>140x140</span></p>
            <div class="coment">
                <h4>{{ comment.user }}</h4>
                <p class="date">{{ comment.date|date('d.m.Y') }}</p>
                <p>{{ comment.comment }}</p>
            </div>
        </article>
    {% endfor %}
{% endif %}

Resources/views/Twig/comments_form.html.twig
<form>
    <p>Поделитесь Вашим мнением об объекте</p>

    <div class="left">
        {{ form_widget(form.comment) }}
    </div>
    <div class="right">
        <a href="#" class="otziv"><span></span>Рекомендую</a>
        <a href="#" class="otziv no"><span></span>Не доволен</a>
        {{ form_widget(form.type) }}
        <a href="#">{{ 'Send'|trans({}, 'hotels') }}</a>
    </div>
    {{ form_widget(form.hotel) }}
    {{ form_widget(form.user) }}
    {{ form_rest(form) }}
</form>

Resources/views/Twig/hotels.html.twig
{% if hotels|length %}
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <th>ID</th>
                <th>{{ 'Title'|trans({}, 'labels') }}</th>
                <th>{{ 'Price'|trans({}, 'labels') }}</th>
                <th>{{ 'Count guests'|trans({}, 'labels') }}</th>
                <th>{{ 'Status'|trans({}, 'labels') }}</th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
            {% for hotel in hotels %}
                <tr>
                    <td>{{ hotel.id }}</td>
                    <td>
                        <a href="{{ url('users_hotels_edit', {id: hotel.id}) }}">
                            {{ hotel.title|locale }}
                        </a>
                    </td>
                    <td>{{ hotel.priceDay|number_format(2, '.', ',') }}</td>
                    <td>{{ hotel.countGuests }}</td>
                    <td>{{ hotel.status }}</td>
                    <td><a href='{{ url('users_hotels_edit', {id: hotel.id}) }}'><span
                                    class="glyphicon lead text-primary glyphicon-pencil"></span></a></td>
                    <td><a href='{{ url('cms_hotels_delete', {id: hotel.id}) }}'><span
                                    class="glyphicon lead text-danger glyphicon-remove-circle"></span></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <p class="bg-danger">
    <h2>{{ 'Hotels not found'|trans({}, 'hotels') }}</h2>
    </p>
{% endif %}

Resources/views/Twig/message.html.twig
{% if message is defined %}
<h3>{{ message|trans({}, 'messages') }}</h3>
{% endif %}

Resources/views/Twig/prices_rules_form.html.twig
{% form_theme form 'HotelsBundle::fields.html.twig' %}
<div class="well well-sm">
    <form method="post">
        <div class="row">
            <div class="col-sm-6">
                {{ form_row(form.date_start) }}
            </div>
            <div class="col-sm-6">
                {{ form_row(form.date_end) }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                {{ form_row(form.min_guests) }}
            </div>
            <div class="col-sm-6">
                {{ form_row(form.max_guests) }}
            </div>
        </div>
        <div class="row">
        {% if form.hotel is defined %}
            <div class="col-sm-6">
                {{ form_row(form.hotel) }}
            </div>
        {% endif %}
        {% if form.room is defined %}
            <div class="col-sm-6">
                {{ form_row(form.room) }}
            </div>
        {% endif %}
            <div class="col-sm-6">
                {{ form_row(form.price) }}
            </div>
        </div>
        {{ form_rest(form) }}
        <div class="row">
            <div class="col-sm-6">
                <input type="submit" class="btn btn-success" value="{{ 'Add'|trans({}, 'labels') }}">
            </div>
            <div class="col-sm-6">
                {{ form_errors(form) }}
            </div>
        </div>
    </form>
</div>

Resources/views/Twig/reservations.html.twig
{% if reservations|length %}
    <table>
        <tr>
            <th>{{ 'ID' }}</th>
            <th>{{ 'reservation.lables.hotel'|trans({}, 'reservations') }}</th>
            <th>{{ 'reservation.lables.room'|trans({}, 'reservations') }}</th>
            <th>{{ 'reservation.lables.guests'|trans({}, 'reservations') }}</th>
            <th>{{ 'reservation.lables.periods'|trans({}, 'reservations') }}</th>
            <th>{{ 'reservation.lables.price'|trans({}, 'reservations') }}</th>
            <th>{{ 'reservation.lables.customer'|trans({}, 'reservations') }}</th>
            <th>{{ 'reservation.lables.status'|trans({}, 'reservations') }}</th>
            <th colspan="2">{{ 'reservation.lables.managment'|trans({}, 'reservations') }}</th>
        </tr>
    {% for reservation in reservations %}
        {% set hotel = hotels[reservation.hotel] %}
        {% set rooms = [] %}
        {% if hotel.rooms|length %}
            {%  set room = hotel.rooms[reservation.room] %}
        {% endif %}
        <tr>
            <td>{{ reservation.id }}</td>
            <td>
                <a href="{{ url('users_hotels') }}">{{ hotel.title|locale }}</a>
            </td>
            <td>
                {% if reservation.room %}
                    <a href="{{ url('users_hotels_rooms', {hotel: hotel.id}) }}">{{ room.title|locale }}</a>
                {% endif %}
            </td>
            <td>{{ reservation.countGuests }}</td>
            <td>{{ reservation.dateStart|date('d.m.Y') }} - {{ reservation.dateEnd|date('d.m.Y') }}</td>
            <td>{{ reservation.price }} &euro;</td>
            <td>
                {{ reservation.customerLastname }} {{ reservation.customerName }}
            </td>
            <td>{{ 'reservation.statuses'|transchoice(reservation.status, {}, 'reservations') }}</td>
            <td>
                {% if (reservation.dateStart)|date('U') > 'now'|date('U') %}
                    <a href="{{ url('users_reservation_edit', {'id': reservation.id}) }}">{{ 'reservation.lables.edit'|trans({}, 'reservations') }}</a>
                {% endif %}
            </td>
            <td>
                {% if (reservation.dateStart)|date('U') > 'now'|date('U') %}
                    <a href="{{ url('users_reservation_delete', {'id': reservation.id}) }}">{{ 'reservation.lables.delete'|trans({}, 'reservations') }}</a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <h4>{{ 'Reservations not found!' }}</h4>
{% endif %}

Resources/views/Twig/rooms.html.twig
{% if rooms|length %}
    <div class="rooms">
    {% for room in hotel.rooms %}
        <div class="room">
            <h4>{{ room.title|locale }}</h4>
            {% if room.services|length %}
                <div class="room-services">
                    {% for service in room.services %}
                        <div class="{% if loop.index0%2 == 0 %}left{% else %}right{% endif %}">
                            {{ service.title|locale }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="room-description">{{ room.descriptions|locale }}</div>
        </div>
    {% endfor %}
    </div>
{% endif %}