Entity/Hotels.php
<?php

namespace CMS\HotelsBundle\Entity;

use CMS\GalleryBundle\Entity\Images;
use CMS\GeoBundle\Entity\Geoobjects;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Hotels
 */
class Hotels
{
    /**
     * @var integer
     */
    protected $id;

    /**
     * @var locale_string
     */
    protected $title;

    /**
     * @var HousingTypes
     */
    protected $housing_type;

    /**
     * @var Cities
     */
    protected $city;

    /**
     * @var Geoobjects
     */
    protected $location;

    /**
     * @var string
     */
    protected $descriptions;

    /**
     * @var ArrayCollection
     */
    protected $photos;

    /**
     * @var float
     */
    protected $rating = 1.0;

    /**
     * @var int
     */
    protected $status = 0;

    /**
     * @var ArrayCollection
     */
    protected $rooms;

    /**
     * @var ArrayCollection
     */
    protected $comments;

    /**
     * @var bool
     */
    protected $is_published = false;

    /**
     * @var bool
     */
    protected $is_deleted = false;

    /**
     * @var \DateTime
     */
    protected $date_create;

    /**
     * @var \DateTime
     */
    protected $date_update;

    /**
     * @var integer
     */
    protected $create_by;

    /**
     * @var integer
     */
    protected $update_by;

    public function __construct()
    {
        $this->rooms = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->photos = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set housing_type
     *
     * @param $housingType
     * @return $this
     */
    public function setHousingType($housingType)
    {
        $this->housing_type = $housingType;

        return $this;
    }

    /**
     * Get housing_type
     *
     * @return \int
     */
    public function getHousingType()
    {
        return $this->housing_type;
    }

    /**
     * @return locale_string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param locale_string $title
     * @return $this
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return int
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param int $city
     * @return $this
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Geoobjects
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * @param Geoobjects $location
     * @return $this
     */
    public function setLocation($location)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getDescriptions()
    {
        return $this->descriptions;
    }

    /**
     * @param mixed $descriptions
     * @return $this
     */
    public function setDescriptions($descriptions)
    {
        $this->descriptions = $descriptions;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getPhotos()
    {
        return $this->photos;
    }

    /**
     * @param ArrayCollection $photos
     * @return $this
     */
    public function setPhotos($photos)
    {
        $this->photos = $photos;

        return $this;
    }

    public function addPhoto(Images $photo)
    {
        $this->photos->add($photo);

        $photo->addHotel($this);
    }

    /**
     * @return float
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * @param float $rating
     * @return $this
     */
    public function setRating($rating)
    {
        $this->rating = $rating;

        return $this;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getRooms()
    {
        return $this->rooms;
    }

    /**
     * @param ArrayCollection $rooms
     * @return $this
     */
    public function setRooms($rooms)
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function addRoom($room)
    {
        $this->rooms[] = $room;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @param ArrayCollection $comments
     * @return $this
     */
    public function setComments($comments)
    {
        $this->comments = $comments;

        return $this;
    }

    public function addComment($comment)
    {
        $this->comments[] = $comment;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsPublished()
    {
        return $this->is_published;
    }

    /**
     * @param boolean $is_published
     * @return $this
     */
    public function setIsPublished($is_published)
    {
        $this->is_published = $is_published;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsDeleted()
    {
        return $this->is_deleted;
    }

    /**
     * @param boolean $is_deleted
     * @return $this
     */
    public function setIsDeleted($is_deleted)
    {
        $this->is_deleted = $is_deleted;

        return $this;
    }

    /**
     * @return int
     */
    public function getCreateBy()
    {
        return $this->create_by;
    }

    /**
     * @param int $create_by
     * @return $this
     */
    public function setCreateBy($create_by)
    {
        $this->create_by = $create_by;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * @param \DateTime $date_create
     * @return $this
     */
    public function setDateCreate($date_create)
    {
        $this->date_create = new \DateTime();

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateUpdate()
    {
        return $this->date_update;
    }

    /**
     * @param \DateTime $date_update
     * @return $this
     */
    public function setDateUpdate($date_update)
    {
        $this->date_update = new \DateTime();

        return $this;
    }

    /**
     * @return int
     */
    public function getUpdateBy()
    {
        return $this->update_by;
    }

    /**
     * @param int $update_by
     * @return $this
     */
    public function setUpdateBy($update_by)
    {
        $this->update_by = $update_by;

        return $this;
    }
}

Form/HotelsType.php
<?php

namespace CMS\HotelsBundle\Form;

use CMS\GalleryBundle\Form\Types\ImagesType;
use CMS\GeoBundle\Form\Types\GeoObjectType;
use CMS\LocalizationBundle\Form\Types\LocaleEntityType;
use CMS\LocalizationBundle\Form\Types\LocaleTextareaType;
use CMS\LocalizationBundle\Form\Types\LocaleTextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HotelsType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', LocaleTextType::class)
            ->add('city', LocaleEntityType::class, array(
                'class' => 'LocalizationBundle:Cities',
                'choice_label' => 'title',
                'empty_data' => null,
                'placeholder' => '',
            ))
            ->add('housing_type', LocaleEntityType::class, array(
                'class' => 'HotelsBundle:HousingTypes',
                'choice_label' => 'title',
                'empty_data' => null,
                'placeholder' => '',
            ))
            ->add('descriptions', LocaleTextareaType::class, array(
                'required' => false
            ))
            ->add('photos', ImagesType::class, [
                'required' => false
            ])
            ->add('location', GeoObjectType::class)
            ->add('is_published')
            ->add('is_deleted');

        if (true === $options['show_rooms']) {
            $builder
                ->add('rooms', CollectionType::class, [
                    'entry_type' => HotelsRoomsType::class
                ]);
        }
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'translation_domain' => 'hotels',
            'data_class' => 'CMS\HotelsBundle\Entity\Hotels',
            'show_rooms' => false
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'cms_hotelsbundle_simple_hotels';
    }
}

Controller/HotelsController.php
<?php

namespace CMS\HotelsBundle\Controller;

use CMS\GalleryBundle\Entity\Images;
use CMS\HotelsBundle\Entity\Hotels;
use CMS\HotelsBundle\Form\HotelWizard\HotelMainType;
use CMS\HotelsBundle\Form\HotelWizard\HotelPhotosType;
use CMS\HotelsBundle\Form\HotelWizard\HotelPlacementType;
use CMS\HotelsBundle\Form\HotelWizard\HotelPriceType;
use CMS\HotelsBundle\Form\HotelWizard\HotelReservationType;
use CMS\HotelsBundle\Form\HotelWizard\HotelRoomsType;
use CMS\HotelsBundle\Form\HotelWizard\HotelServicesType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class HotelsController
 * @package CMS\HotelsBundle\Controller
 */
class HotelsController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction()
    {
        $service = $this->get('cms.hotels.service');

        return $this->render('HotelsBundle:Hotels:list.html.twig', array(
            'hotels' => $service->findAll()
        ));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function createAction(Request $request)
    {
        $service = $this->get('cms.hotels.service');

        $form = $service->generateForm();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $data = $form->getData();

                $service->create($data);

                if (!$data->getHousingType()->getIsHaveRooms()) {
                    return $this->redirect($this->generateUrl('cms_hotels_rooms_create', ['hotel' => $data->getId()]));
                }

                return $this->redirect($this->generateUrl('cms_hotels_list'));
            }
        }

        return $this->render('HotelsBundle:Hotels:edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function editAction(Request $request, $id)
    {
        $service = $this->get('cms.hotels.service');

        /** @var Hotels $hotel */
        if (null === ($hotel = $service->getHotelById($id))) {
            throw $this->createNotFoundException('Hotel not found');
        }

        $form = $service->generateForm($hotel);

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $service->update($form->getData());

                return $this->redirect($this->generateUrl('cms_hotels_list'));
            }
        }

        return $this->render('HotelsBundle:Hotels:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction(Request $request, $id)
    {
        $hotelsService = $this->get('cms.hotels.service');

        $registry = $this->getDoctrine();

        if (null === ($hotel = $hotelsService->getHotelById($id, true))) {
            throw $this->createNotFoundException('Hotel not found!');
        }

        $hotelsRoomsEM = $registry->getManagerForClass(Hotels::class);
        $hotelsEM = $registry->getManagerForClass(Hotels::class);
        $photosEM = $registry->getManagerForClass(Images::class);

        foreach ($hotel->getRooms() as $room) {
            $hotelsRoomsEM->remove($room);
        }

        foreach ($hotel->getPhotos() as $photo) {
            $photosEM->remove($photo);
        }

        $hotelsEM->remove($hotel);

        $photosEM->flush();
        $hotelsRoomsEM->flush();
        $hotelsEM->flush();

        return $this->redirect($this->generateUrl('cms_hotels_list'));
    }

    /**
     * @param Request $request
     * @param $hotel
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function calendarAction(Request $request, $hotel)
    {
        $hotelsService = $this->get('cms.hotels.service');

        if (null === ($hotel = $hotelsService->getHotelById($hotel, true))) {
            throw $this->createNotFoundException('Hotel not found!');
        }

        if (null !== ($rooms = $hotel->getRooms())) {
            $rooms = $rooms->toArray();
        }

        $dateNow = new \DateTime();
        $year = $request->query->get('year', $dateNow->format('Y'));

        return $this->render('HotelsBundle:Hotels:calendar.html.twig', array(
            'hotel' => $hotel,
            'rooms' => $rooms,
            'year' => $year
        ));
    }
}

Resources/views/Hotels/calendar.html.twig
{% extends "DashboardBundle:Layout:base.html.twig" %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts
    '@jqueryui_js'
    '@jqueryui_mouse_js'
    '@jqueryui_selectable_js'
    '@jqueryui_tooltip_js'
    '@jqueryui_positon_js'
    '@HotelsBundle/Resources/public/js/hotels_prices.js'
    '@HotelsBundle/Resources/public/js/hotel_calendar.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}

    <script type="text/javascript">
        $(document).ready(function () {
            $('.prices-calendar').hotelsPrices();
            $('.hotel_calendar').hotelsCalendar({
                'hotelCalendarRoute': 'cms_hotels_calendar',
                'hotelRoomCalendarRoute': 'cms_hotels_rooms_calendar'
            });
        });
    </script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {% stylesheets
    '@HotelsBundle/Resources/public/css/datepicker.css'
    '@HotelsBundle/Resources/public/css/bootstrap_castom_table.css'
    '@HotelsBundle/Resources/public/css/tooltip.css' %}
    <link rel="stylesheet" href="{{ asset_url }}"/>

    {% endstylesheets %}
{% endblock %}

{% block body %}
    {% embed 'HotelsBundle::main.html.twig' %}
        {% block panelButtons %}

        {% endblock %}

        {% block main %}
            <div class="well well-sm">
                <form method="get">
                    <div class="row">
                        <div class="col-sm-6">
                            <select name="year" class="form-control">
                                {% for year in ('now'|date('Y'))..(('now'|date('Y'))+10) %}
                                    <option value="{{ year }}" {% if app.request.get('year') == year %} selected="selected"{% endif %}>{{ year }}</option>s
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-sm-6">
                            <input type="submit" class="btn btn-success" value="Ok">
                        </div>
                    </div>
                </form>
            </div>
            {{ show_hotel_calendar(year, hotel, rooms) }}
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/Hotels/edit.html.twig
{% extends 'DashboardBundle:Layout:base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts '@file_uploader'
    '@jqueryui_datepicker_js'
    'bundles/localization/js/localization_form.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}

    <script type="text/javascript">
        $(document).ready(function () {
            $('.datepicker').datepicker({dateFormat: 'dd.mm.yy'});
        });
    </script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {% stylesheets
    '@fileupload_css' %}
    <link rel="stylesheet" href="{{ asset_url }}"/>
    {% endstylesheets %}
{% endblock %}

{% block body %}
    {% embed "HotelsBundle::main.html.twig" %}
        {% block main %}
            <div class="row">
                {% form_theme form 'HotelsBundle::fields.html.twig' %}
                <div class="col-md-12">
                    {{ show_locale_tabs() }}
                    <br/>
                    <form method="post" {{ form_enctype(form) }} class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                {{ form_errors(form) }}
                                {{ form_row(form.title,{
                                    'label': 'Title'|trans({},'messages'),
                                }) }}
                                {{ form_row(form.city,{
                                    'label': 'City'|trans({},'messages'),
                                }) }}
                                {{ form_row(form.descriptions,{
                                    'label': 'Descriptions'|trans({},'messages'),
                                }) }}
                                {{ form_rest(form) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="well well-sm text-right">
                                    <input type="submit" class="btn btn-primary btn-sm" data-loading-text="Saving..."
                                           value="{{ 'Save'|trans({}, 'systems') }}"/>
                                    <a href="javascript:history.go(-1)"
                                       class="btn btn-default btn-sm">{{ 'Cancel'|trans({}, 'systems') }}</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/Hotels/list.html.twig
{% extends "DashboardBundle:Layout:base.html.twig" %}

{% block body %}
    {% embed 'HotelsBundle::main.html.twig' %}
        {% block panelButtons %}
            <a href="{{ url('cms_hotels_create') }}"
               class="glyphicon glyphicon-plus btn btn-success btn-xs">{{ 'Add'|trans }}</a>
        {% endblock %}

        {% block main %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <th><input type="checkbox" data-action="selectAll"/></th>
                    <th>ID</th>
                    <th>{{ 'Title'|trans }}</th>
                    <th>{{ 'Status'|trans }}</th>
                    <th>{{ 'Create by'|trans }}</th>
                    <th>{{ 'Date'|trans }}</th>
                    <th>{{ 'Is published'|trans }}</th>
                    <th>{{ 'Is deleted'|trans }}</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    </thead>
                    <tbody>
                    {% for hotel in hotels %}
                        <tr>
                            <td><input type="checkbox" value="{{ hotel.id }}" name="mark[]"/></td>
                            <td>{{ hotel.id }}</td>
                            <td>
                                <a href="{{ url('cms_hotels_edit', {id: hotel.id}) }}">
                                    {{ hotel.title|locale }}
                                </a>
                            </td>
                            <td>{{ hotel.status }}</td>
                            <td>{{ hotel.createBy }}</td>
                            <td>{{ hotel.dateCreate|date('d.m.Y') }}</td>
                            <td>{{ hotel.isPublished }}</td>
                            <td>{{ hotel.isDeleted }}</td>
                            <td>
                                <a href="{{ url('cms_hotels_calendar', {'hotel': hotel.id}) }}">{{ 'Calendar'|trans({}, 'hotels') }}</a>
                            </td>
                            <td>
                                <a href="{{ url('cms_hotels_rooms_list', {'hotel': hotel.id}) }}">{{ 'Rooms'|trans({}, 'labels') }}</a>
                            </td>
                            <td>
                                <a href="{{ url('cms_hotels_comments_list', {'hotel': hotel.id}) }}">{{ 'Comments'|trans({}, 'labels') }}</a>
                            </td>
                            <td><a href='{{ url('cms_hotels_edit', {id: hotel.id}) }}'><span
                                            class="glyphicon lead text-primary glyphicon-pencil"></span></a></td>
                            <td><a href='{{ url('cms_hotels_delete', {id: hotel.id}) }}'><span
                                            class="glyphicon lead text-danger glyphicon-remove-circle"></span></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/Hotels/select_type_produced_hotel.html.twig
{% extends "DashboardBundle:Layout:base.html.twig" %}

{% block body %}
    {% embed 'HotelsBundle::main.html.twig' %}
        {% block main %}
            <div>
                {% if types|length %}
                    <ul>
                        {% for type in types %}
                            <li>
                                <a href="{{ url('cms_hotels_create', {'housingTypeId': type.id}) }}">{{ type.title|locale }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <h3>{{ 'Housing types is not defined'|trans({}, 'hotels') }}</h3>
                {% endif %}
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/Hotels/wizard.html.twig
{% extends 'DashboardBundle:Layout:base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts '@file_uploader'
    '@jqueryui_datepicker_js'
    'bundles/localization/js/localization_form.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}

    <script type="text/javascript">
        $(document).ready(function () {
            $('.datepicker').datepicker({dateFormat: 'dd.mm.yy'});
        });
    </script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {% stylesheets
    '@fileupload_css' %}
    <link rel="stylesheet" href="{{ asset_url }}"/>
    {% endstylesheets %}
{% endblock %}

{% block body %}
    {% embed "HotelsBundle::main.html.twig" %}
        {% block main %}
            <div class="row">
                {% form_theme form 'HotelsBundle::fields.html.twig' %}
                <div class="col-md-12">
                    {{ show_locale_tabs() }}
                    <br/>

                    <form method="post" {{ form_enctype(form) }} class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                {{ form_errors(form) }}
                                {{ form_rest(form) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="well well-sm text-right">
                                    <input type="submit" class="btn btn-primary btn-sm" data-loading-text="Saving..."
                                           value="{{ 'Save'|trans({}, 'systems') }}"/>
                                    <a href="javascript:history.go(-1)"
                                       class="btn btn-default btn-sm">{{ 'Cancel'|trans({}, 'systems') }}</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}